# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://www.bailei.tech/blog
date_format: "ordinal"
title: 简爱
subtitle: "学习改变命运"
description: "我的个人博客"
keywords: 简爱, jian ai, jalogin, bailei
timezone: Asia/hangzhou
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: bai lei
organization: bailei.tech
organization_url: http://www.bailei.tech/blog
github_username: burning-magina
location: shanxi, China
email: yuanquan.ni@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: burning-magina/blog

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: burning-magina
    repo: blog_comments
    oauth:
        client_id: 587e52552d56bf46fe7c
        client_secret: f2496884035944901f2b02b63172d1d86444b939
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: burning-magina
    repo: blog_comments
    clientID: 587e52552d56bf46fe7c
    clientSecret: f2496884035944901f2b02b63172d1d86444b939
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
